services:
  auth-service:
    container_name: ${AUTH_SERVICE_NAME:-auth-service}
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - ${AUTH_SERVICE_PORT:-3001}:${AUTH_SERVICE_PORT:-3001}
    volumes:
      - ./services/auth-service/:/app/
      - /app/node_modules
    environment:
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT:-3001}
      JWT_SECRET: ${JWT_SECRET}
    command: node src/server.js
  movie-service:
    container_name: ${MOVIE_SERVICE_NAME:-movie-service}
    build:
      context: ./services/movie-service
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - ${MOVIE_SERVICE_PORT:-3002}:${MOVIE_SERVICE_PORT:-3002}
      - 9229:9229
      - 9230:9230
    depends_on:
      - auth-service
      - mongodb
    volumes:
      - ./services/movie-service/src/:/app/src/
      - /app/node_modules
    environment:
      AUTH_HOST: ${AUTH_SERVICE_NAME:-auth-service}
      AUTH_PORT: ${AUTH_SERVICE_PORT:-3001}
      MOVIE_SERVICE_PORT: ${MOVIE_SERVICE_PORT:-3002}
      JWT_SECRET: ${JWT_SECRET}
      OMDB_APIKEY: ${OMDB_APIKEY}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      DB_HOST: ${MONGODB_SERVICE_NAME:-mongodb}
      DB_PORT: ${DB_PORT:-27017}
      DB_NAME: ${EXAMPLE_DB_NAME:-example-database}
    command: nodemon --trace-warnings --inspect=0.0.0.0:9229 src/server.js
  mongodb:
    container_name: ${MONGODB_SERVICE_NAME:-mongodb}
    image: mongo
    restart: always
    ports:
      - ${DB_PORT:-27017}:${DB_PORT:-27017}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${EXAMPLE_DB_NAME:-example-database}
      