name: Docker test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build & run the stack
        run: JWT_SECRET=$JWT_SECRET MONGODB_USERNAME=$MONGODB_USERNAME MONGODB_PASSWORD=$MONGODB_PASSWORD OMDB_APIKEY=$OMDB_APIKEY docker-compose up --build -d
        env:
          AUTH_SERVICE_PORT: 3001
          MOVIE_SERVICE_PORT: 3002
          EXAMPLE_DB_NAME: "example-database"

      - name: Run the tests on movie-service
        run: docker-compose run --rm --entrypoint "" movie-service npm test
        env:
          JWT_SECRET: $JWT_SECRET
          MONGODB_USERNAME: $MONGODB_USERNAME
          MONGODB_PASSWORD: $MONGODB_PASSWORD
          OMDB_APIKEY: $OMDB_APIKEY
          AUTH_SERVICE_PORT: 3001
          MOVIE_SERVICE_PORT: 3002
          EXAMPLE_DB_NAME: "example-database"